name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build
        run: ./gradlew clean build
